export const authConstants = {
	AUTHENTICATE_USER: 'AUTHENTICATE_USER',
	AUTHENTICATE_ERROR: 'AUTHENTICATE_ERROR',
	REGISTER_USER: 'REGISTER_USER',
	REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
	LOGIN_USER: 'LOGIN_USER',
	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
	LOGOUT_USER: 'LOGOUT_USER',
	// LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	// LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	// LOGIN_FAILURE: 'USERS_LOGIN_FAILURE'

}
// export const geolocationConstants = {
// 	GET_GEOLOCATION = 'GET_GEOLOCATION',
// 	GEOLOCATION_DENIED = 'GEOLOCATION_DENIED'
// }

// export const weatherConstants = {
// 	GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER',
// 	GET_FORECAST = 'GET_FORECAST',
// 	SEARCH_WEATHER_LOCATION = 'SEARCH_WEATHER',
// 	UPDATE_METRIC = 'UPDATE_METRIC',
// 	UPDATE_IMPERIAL = 'UPDATE_IMPERIAL'
// }

// export const todoConstants = {
// 	GET_ONE_TODO = 'GET_ONE_TODO',
// 	GET_ALL_TODOS = 'GET_ALL_TODOS',
// 	CREATE_TODO = 'CREATE_TODO',
// 	EDIT_TODO = 'EDIT_TODO',
// 	REMOVE_TODO = 'REMOVE_TODO',
// 	TODO_ERROR = 'TODO_ERROR'

// }
// export const userConstants = {
// 	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
// 	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
// 	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

// 	LOGOUT: 'USERS_LOGOUT',

// 	GETALL_REQUEST: 'USERS_GETALL_REQUEST',
// 	GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
// 	GETALL_FAILURE: 'USERS_GETALL_FAILURE'
// }